name: Build Eclipse eMoflon
on: [push]
jobs:
  build-linux:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Linux)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run build script
        run: chmod +x linux.sh && ./linux.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-linux-user.zip
          path: eclipse-emoflon-linux-user.zip
