name: Build Eclipse eMoflon
on:
  push:
    # Run pipeline for commits on branch 'main' and on 'testing/<stuff>'
    branches:
      - main
      - 'testing/**'

jobs:
  # Build Eclipse eMoflon Linux user
  build-linux-user:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Linux user)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run build script
        run: chmod +x linux.sh && ./linux.sh -m user
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-linux-user
          path: eclipse-emoflon-linux-user.zip

  # Build Eclipse eMoflon Linux dev
  build-linux-dev:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Linux dev)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run build script
        run: chmod +x linux.sh && ./linux.sh -m dev
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-linux-dev
          path: eclipse-emoflon-linux-dev.zip

  # Build Eclipse eMoflon Linux user CI
  build-linux-user-ci:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Linux user CI)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run build script
        run: chmod +x linux.sh && ./linux.sh -m user --skip-theme
      - name: Rename ZIP archive
        run: mv eclipse-emoflon-linux-user.zip eclipse-emoflon-linux-user-ci.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-linux-user-ci
          path: eclipse-emoflon-linux-user-ci.zip

  # Build Eclipse eMoflon Linux dev CI
  build-linux-dev-ci:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Linux dev CI)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run build script
        run: chmod +x linux.sh && ./linux.sh -m dev --skip-theme
      - name: Rename ZIP archive
        run: mv eclipse-emoflon-linux-dev.zip eclipse-emoflon-linux-dev-ci.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-linux-dev-ci
          path: eclipse-emoflon-linux-dev-ci.zip

  # Build Eclipse eMoflon Windows user
  build-windows-user:
    runs-on: [self-hosted, windows, x64]
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Windows user)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run build script
        run: |
          echo "C:\Program Files\Eclipse Foundation\jdk-16.0.2.7-hotspot\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          bash ./windows.sh -m user
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-windows-user
          path: eclipse-emoflon-windows-user.zip

  # Build Eclipse eMoflon Windows dev
  build-windows-dev:
    runs-on: [self-hosted, windows, x64]
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Windows dev)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run build script
        run: |
          echo "C:\Program Files\Eclipse Foundation\jdk-16.0.2.7-hotspot\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          bash ./windows.sh -m dev
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-windows-dev
          path: eclipse-emoflon-windows-dev.zip
