name: Build Eclipse eMoflon
on:
  push:
    # Run pipeline for commits on branch 'main' and on 'testing/<stuff>'
    branches:
      - main
      - 'testing/**'
    # Run pipeline for release tags
    tags:
      - 'v*.*.*'

env:
  # Eclipse version to use in this CI
  VERSION: "2021-12"

jobs:
  # Create splash image
  create-splash-image:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Start message
        run: echo "Creating splash image for version $VERSION."
      - name: Run splash creator script
        run: chmod +x splash.sh && ./splash.sh img $VERSION
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: splash.bmp
          path: splash.bmp

  # Build Eclipse eMoflon Linux user
  build-linux-user:
    needs: [create-splash-image]
    runs-on: [ubuntu-20.04]
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Linux user)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Download splash image
        uses: actions/download-artifact@v2
        with:
          name: splash.bmp
      - name: Run build script
        run: chmod +x build.sh && ./build.sh -m user -o linux
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-linux-user
          path: eclipse-emoflon-linux-user.zip

  # Build Eclipse eMoflon Linux dev
  build-linux-dev:
    needs: [create-splash-image]
    runs-on: [ubuntu-20.04]
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Linux dev)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Download splash image
        uses: actions/download-artifact@v2
        with:
          name: splash.bmp
      - name: Run build script
        run: chmod +x build.sh && ./build.sh -m dev -o linux
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-linux-dev
          path: eclipse-emoflon-linux-dev.zip

  # Build Eclipse eMoflon Linux user CI
  build-linux-user-ci:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Linux user CI)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run build script
        run: chmod +x build.sh && ./build.sh -m user -o linux --skip-theme
      - name: Rename ZIP archive
        run: mv eclipse-emoflon-linux-user.zip eclipse-emoflon-linux-user-ci.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-linux-user-ci
          path: eclipse-emoflon-linux-user-ci.zip

  # Build Eclipse eMoflon Linux dev CI
  build-linux-dev-ci:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Linux dev CI)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run build script
        run: chmod +x build.sh && ./build.sh -m dev -o linux --skip-theme
      - name: Rename ZIP archive
        run: mv eclipse-emoflon-linux-dev.zip eclipse-emoflon-linux-dev-ci.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-linux-dev-ci
          path: eclipse-emoflon-linux-dev-ci.zip

  # Build Eclipse eMoflon Linux dev HiPE
  build-linux-dev-hipe:
    needs: [create-splash-image]
    runs-on: [ubuntu-20.04]
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Linux dev HiPE)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Download splash image
        uses: actions/download-artifact@v2
        with:
          name: splash.bmp
      - name: Run build script
        run: chmod +x build.sh && ./build.sh -m hipedev -o linux
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-linux-dev-hipe
          path: eclipse-emoflon-linux-dev-hipe.zip

  # Build Eclipse eMoflon macOS user
  build-macos-user:
    needs: [create-splash-image]
    runs-on: [macos-latest]
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon macOS user)."
      - name: Install dependencies
        run: |
          brew update
          brew install p7zip coreutils grep wget curl
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Download splash image
        uses: actions/download-artifact@v2
        with:
          name: splash.bmp
      - name: Run build script
        run: chmod +x build.sh && ./build.sh -m user -o macos
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-macos-user
          path: eclipse-emoflon-macos-user.zip

  # Build Eclipse eMoflon Windows user
  build-windows-user:
    needs: [create-splash-image]
    runs-on: [windows-2022]
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Windows user)."
      - name: Install dependencies
        run: |
          choco install wget curl unzip zip --no-progress
      - name: Install correct Java version
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Fix Git line endings
        run: git config --global core.autocrlf input
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Download splash image
        uses: actions/download-artifact@v2
        with:
          name: splash.bmp
      - name: Run build script
        run: |
          bash ./build.sh -m user -o windows
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-windows-user
          path: eclipse-emoflon-windows-user.zip

  # Build Eclipse eMoflon Windows dev
  build-windows-dev:
    needs: [create-splash-image]
    runs-on: [windows-2022]
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Windows dev)."
      - name: Install dependencies
        run: |
          choco install wget curl unzip zip --no-progress
      - name: Install correct Java version
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Fix Git line endings
        run: git config --global core.autocrlf input
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Download splash image
        uses: actions/download-artifact@v2
        with:
          name: splash.bmp
      - name: Run build script
        run: |
          bash ./build.sh -m dev -o windows
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-windows-dev
          path: eclipse-emoflon-windows-dev.zip

  # Build Eclipse eMoflon Windows dev HiPE
  build-windows-dev-hipe:
    needs: [create-splash-image]
    runs-on: [windows-2022]
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Windows dev HiPE)."
      - name: Install dependencies
        run: |
          choco install wget curl unzip zip --no-progress
      - name: Install correct Java version
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Fix Git line endings
        run: git config --global core.autocrlf input
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Download splash image
        uses: actions/download-artifact@v2
        with:
          name: splash.bmp
      - name: Run build script
        run: |
          bash ./build.sh -m hipedev -o windows
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-windows-dev-hipe
          path: eclipse-emoflon-windows-dev-hipe.zip

  # Create a release if running on tag
  create-release:
    needs: [build-linux-user, build-linux-dev, build-linux-user-ci, build-linux-dev-ci, build-linux-dev-hipe, build-windows-user, build-windows-dev, build-windows-dev-hipe]
    runs-on: [ubuntu-20.04]
    # Only run on tags
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Collect artifacts
        uses: actions/download-artifact@master
      - name: Release eclipse-emoflon-linux
        uses: softprops/action-gh-release@v1
        with:
          files: |
            eclipse-emoflon-linux-user/eclipse-emoflon-linux-user.zip
            eclipse-emoflon-linux-dev/eclipse-emoflon-linux-dev.zip
      - name: Release eclipse-emoflon-linux-ci
        uses: softprops/action-gh-release@v1
        with:
          files: |
            eclipse-emoflon-linux-user-ci/eclipse-emoflon-linux-user-ci.zip
            eclipse-emoflon-linux-dev-ci/eclipse-emoflon-linux-dev-ci.zip
      - name: Release eclipse-emoflon-windows
        uses: softprops/action-gh-release@v1
        with:
          files: |
            eclipse-emoflon-windows-user/eclipse-emoflon-windows-user.zip
            eclipse-emoflon-windows-dev/eclipse-emoflon-windows-dev.zip
      - name: Release eclipse-emoflon-dev-hipe
        uses: softprops/action-gh-release@v1
        with:
          files: |
            eclipse-emoflon-linux-dev-hipe/eclipse-emoflon-linux-dev-hipe.zip
            eclipse-emoflon-windows-dev-hipe/eclipse-emoflon-windows-dev-hipe.zip
